# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binary_gap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='binary_gap.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x62inary_gap.proto\x12\x07\x65xample\"\"\n\x10\x42inaryGapRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"$\n\x11\x42inaryGapResponse\x12\x0f\n\x07message\x18\x01 \x01(\x03\x32X\n\x10\x42inaryGapService\x12\x44\n\tBinaryGap\x12\x19.example.BinaryGapRequest\x1a\x1a.example.BinaryGapResponse\"\x00\x62\x06proto3')
)




_BINARYGAPREQUEST = _descriptor.Descriptor(
  name='BinaryGapRequest',
  full_name='example.BinaryGapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='example.BinaryGapRequest.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=63,
)


_BINARYGAPRESPONSE = _descriptor.Descriptor(
  name='BinaryGapResponse',
  full_name='example.BinaryGapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.BinaryGapResponse.message', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['BinaryGapRequest'] = _BINARYGAPREQUEST
DESCRIPTOR.message_types_by_name['BinaryGapResponse'] = _BINARYGAPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BinaryGapRequest = _reflection.GeneratedProtocolMessageType('BinaryGapRequest', (_message.Message,), dict(
  DESCRIPTOR = _BINARYGAPREQUEST,
  __module__ = 'binary_gap_pb2'
  # @@protoc_insertion_point(class_scope:example.BinaryGapRequest)
  ))
_sym_db.RegisterMessage(BinaryGapRequest)

BinaryGapResponse = _reflection.GeneratedProtocolMessageType('BinaryGapResponse', (_message.Message,), dict(
  DESCRIPTOR = _BINARYGAPRESPONSE,
  __module__ = 'binary_gap_pb2'
  # @@protoc_insertion_point(class_scope:example.BinaryGapResponse)
  ))
_sym_db.RegisterMessage(BinaryGapResponse)



_BINARYGAPSERVICE = _descriptor.ServiceDescriptor(
  name='BinaryGapService',
  full_name='example.BinaryGapService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=103,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='BinaryGap',
    full_name='example.BinaryGapService.BinaryGap',
    index=0,
    containing_service=None,
    input_type=_BINARYGAPREQUEST,
    output_type=_BINARYGAPRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BINARYGAPSERVICE)

DESCRIPTOR.services_by_name['BinaryGapService'] = _BINARYGAPSERVICE

# @@protoc_insertion_point(module_scope)
