# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import binary_gap_pb2 as binary__gap__pb2


class BinaryGapServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BinaryGap = channel.unary_unary(
        '/example.BinaryGapService/BinaryGap',
        request_serializer=binary__gap__pb2.BinaryGapRequest.SerializeToString,
        response_deserializer=binary__gap__pb2.BinaryGapResponse.FromString,
        )


class BinaryGapServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BinaryGap(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BinaryGapServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BinaryGap': grpc.unary_unary_rpc_method_handler(
          servicer.BinaryGap,
          request_deserializer=binary__gap__pb2.BinaryGapRequest.FromString,
          response_serializer=binary__gap__pb2.BinaryGapResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'example.BinaryGapService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
